# Generated by Django 3.2.19 on 2025-01-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relaydata',
            name='state',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='relaydata',
            name='timestamp',
            field=models.CharField(max_length=255),
        ),
    ]
